# Specific for azure

version: '3.5' # specify docker-compose version

services:
  songifyweb:
    image: ${IMAGE_WEB:-web}
    build:
      context: .
      dockerfile: Dockerfile
    hostname: ${CONTAINER_WEB:-web}
    container_name: ${CONTAINER_WEB:-web}
    ports:
      - "80:80"
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - DB_HOST=${DB_HOST:-mysqlServer}
      - DB_NAME=${DB_NAME:-dummyDB}
      - DB_USERNAME=${DB_USERNAME:-foo}
      - DB_PASSWORD=${DB_PASSWORD:-bar}
      - TIMEZONE=${TIMEZONE:-UTC}