version: '3.5' # specify docker-compose version

networks:
  backend:

volumes:
  database: {}

services:
  songify-web:
    image: songify-web
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - environment=${ENVIRONMENT}
    hostname: ${DOCKER_CONTAINER_WEB}
    container_name: ${DOCKER_CONTAINER_WEB}
    expose:
      - 80
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - DB_HOST=${DOCKER_CONTAINER_DB}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - TIMEZONE=${TIMEZONE}
    ports:
      - "80:80"
    volumes:
      - ./src/public:/var/www/html
    depends_on:
      - songify-mysql
      - songify-phpmyadmin
    networks:
      - backend

  songify-mysql:
    image: mysql:5.7
    hostname: ${DOCKER_CONTAINER_DB}
    container_name: ${DOCKER_CONTAINER_DB}
    volumes:
      - ./db/seedDB/songify.sql:/docker-entrypoint-initdb.d/songify.sql
      - database:/var/lib/mysql
    expose:
      - 3306
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD_ROOT}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      - backend

  songify-phpmyadmin:
    image: phpmyadmin
    container_name: ${DOCKER_CONTAINER_PA}
    environment:
      PMA_ARBITRARY: 1
      PMA_HOSTS: ${DOCKER_CONTAINER_DB}
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
      TZ: ${TIMEZONE}
    expose:
      - 80
    ports:
      - "8083:80"
    networks:
      - backend