version: '3.5' # specify docker-compose version

networks:
  backend:

volumes:
  database: {}

services:
  songifyweb:
    image: ${IMAGE_WEB}
    build:
      context: .
      dockerfile: Dockerfile
    hostname: ${CONTAINER_WEB}
    container_name: ${CONTAINER_WEB}
    expose:
      - 80
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PASSWORD_ROOT=${DB_PASSWORD_ROOT}
      - TIMEZONE=${TIMEZONE}
    ports:
      - "80:80"
    volumes:
      - ./src/public:/var/www/html
    depends_on:
      - mysql
      - phpmyadmin
    networks:
      - backend

  mysql:
    image: mysql:5.7
    hostname: ${CONTAINER_DB}
    container_name: ${CONTAINER_DB}
    volumes:
      - ./db/seedDB/songify.sql:/docker-entrypoint-initdb.d/songify.sql
      - database:/var/lib/mysql
    expose:
      - 3306
    environment:
      - MYSQL_HOST=${DB_HOST}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD_ROOT}
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin
    container_name: ${CONTAINER_PA}
    environment:
      PMA_ARBITRARY: 1
      PMA_HOSTS: ${DB_HOST}
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
      TZ: ${TIMEZONE}
    expose:
      - 80
    ports:
      - "8083:80"
    networks:
      - backend