# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App

on:
  push:
    branches:
      - main

env:
  IMAGE_WEB: ${{ secrets.IMAGE_WEB }}
  ACR_REGISTRY: ${{ secrets.ACR_REGISTRY }}

jobs:
  build:
    name: Build and Push Image
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout main branch from GitHub
        uses: actions/checkout@v2

      - name: Log in to the Azure Container Registry
        run:  echo ${{ secrets.ACR_REGISTRY_PASSWORD }} | docker login ${{ env.ACR_REGISTRY }} --username ${{ secrets.ACR_REGISTRY_USERNAME }} --password-stdin

      - name: Build Docker Image
        run: docker-compose -f docker-compose.azure.yml build          # Build the azure application image using docker-compose

      - name: Push Docker Image to ACR
        run: |

          # Tag the image
          docker tag ${{ env.IMAGE_WEB }} ${{ env.ACR_REGISTRY }}/${{ env.IMAGE_WEB }}

          # Push the image
          docker push ${{ env.ACR_REGISTRY }}/${{ env.IMAGE_WEB }}
          
          # Logout from ACR
          docker logout ${{ env.ACR_REGISTRY }}